import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Firstsection from "@/components/Firstsection";
import Emoji from "@/components/Emoji";
import Secondsection from "@/components/Secondsection";
import Thirdsection from "@/components/Thirdsection";
import { useEffect, useRef } from 'react';


export default function Home() {



  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="gen_landing_page_wrapper" >
          <Firstsection/>
          <Secondsection/>
          <Thirdsection />
      </div>
    </>
  );
}
